server:
  port: 8082
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driverClassName: org.h2.Driver

    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto=update:

      #spring:
  #  security:
  #    user:
  #      name: 12345
  #      password: 12345
  #      roles: ADMIN,USER
  #security:
  #  oauth2:
  #    client:
  #      client-id: mobile
  #      client-secret: pin
  #      access-token-validity-seconds: 3600
  #      authorized-grant-types: refresh_token,authorization_code,password,client_credentials
  #      scope: READ,WRITE
  #    authorization:
  #      check-token-access: permitALL

